lint.select = ["E", "W", "F", "I", "N", "B", "COM", "UP"]
line-length = 120
show-fixes = true
output-format = "full"
indent-width = 4
lint.ignore = ["B008"]
lint.task-tags = ["NOTE", "TODO"]

[lint.per-file-ignores]
"__init__.py" = ["D104"]

[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
lines-after-imports = 2
lines-between-types = 1
no-lines-before = ["third-party", "first-party"]

[lint.pycodestyle]
max-doc-length = 120

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"