defaults:
  - _self_
  - training: default
  - agent: dql
  - network: dqn
  - memory: replay_buffer
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

device: cuda:0
seed: 1234
verbose : True
env: CartPole-v1
bins: 0

hydra:
  run:
    dir: src/outputs/${agent.name}/