defaults:
  - _self_
  - env: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

device: cuda:0

agent: 'rainbow_test'

episodes: 100
episode_max_steps: 200
show_figures: True
hockey : False
render: True
silent: False

hydra:
  output_subdir: null
  run:
    dir: .