defaults:
  - _self_
  - agent: default
  - env: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

device: cuda:0
seed: 1234
verbose : True
env: CartPole-v1

hydra:
  run:
    dir: src/outputs/${agent.name}/