defaults:
  - _self_
  - agent: tdmpc
  - env: hockey-vs-basic
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

device: cuda:0
seed: 1234
verbose : True
env: Pendulum-v1

hydra:
  run:
    dir: src/outputs/${agent.name}/