defaults:
  - _self_
  - training: default
  - agent: dql
  - network: dqn
  - memory: replay_buffer
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

device : cuda:0
seed: 1234
env: CartPole-v1
memory: 

hydra:
  verbose: False
  run:
    dir: src/outputs/${agent.name}/