defaults: 
  - memory: replay_buffer
  - training: default

# type: DDPG Agent
_target_: agents.DDPG
_recursive_: False
name: DDPG
hidden_size: 256
actor_learning_rate: 1e-4
critic_learning_rate: 1e-3
gamma: 0.99
tau: 1e-2
requires_continues_action_space: True