defaults: 
  - memory: replay_buffer
  - training: default

mode: train # train/test or opponent

# type: SAC Agent
_target_: agents.sac.SAC
_recursive_: False
name: SAC
hidden_size: 256
actor_learning_rate: 1e-4
critic_learning_rate: 1e-3
gamma: 0.99
tau: 1e-2
alpha: 0.2
requires_continues_action_space: True