# @package _global_

defaults:
  - override /env: hockey

agent: 'rainbow_hockey_bot'

episodes: 100
episode_max_steps: 400
show_figures: True
hockey : True
render: False
env:
  opponent:
    weak: True
