# @package _global_

defaults:
  - override /env: hockey

agent: 'rainbow_hockey_bot'

episodes: 5
episode_max_steps: 400
show_figures: True
hockey : True
render: True
env:
  opponent:
    weak: False
